server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: MrDiipo
    password: MrDiipo
    url: jdbc:mysql://localhost:3306/registration

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true

  mail:
    host: localhost
    port: 1825
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
